services:
  beaverhabits:
    container_name: habitstracker
    user: 1000:1000 # User permissions of your docker or default user.
    environment:
      # See the note below to find all the environment variables
      - HABITS_STORAGE=USER_DISK # DATABASE stores in a single SQLite database named habits.db. USER_DISK option saves in a local json file.
      # Skip authentication
      - TRUSTED_LOCAL_EMAIL=pepuhodaniel93@gmail.com
      - INDEX_HABIT_DATE_COLUMNS=7
    volumes:
      - .:/app/.user/ # Change directory to match your docker file scheme.
    ports:
      - 8080:8080
    restart: unless-stopped
    image: daya0576/beaverhabits:latest
